### ISSUE TITLE
DH interface not building because JSON version of schema has NaN values

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs6.2_release_candidate#40]
```shell
npm run build -- \
  --outDir ../dist/__data_harmonizer \
  --base /mixs6.2_release_candidate/__data_harmonizer/
```

> 2023-10-03T14:50:31.7455664Z shell: /usr/bin/bash -e {0}
> 2023-10-03T14:50:31.7455936Z env:
> 2023-10-03T14:50:31.7456235Z   pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
> 2023-10-03T14:50:31.7456610Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
> 2023-10-03T14:50:31.7456914Z   VENV: .venv/bin/activate
> 2023-10-03T14:50:31.7457142Z ##[endgroup]
> 2023-10-03T14:50:36.8080841Z 
> 2023-10-03T14:50:36.8082077Z > dh-testing-web@0.0.0 build
> 2023-10-03T14:50:36.8082892Z > vite build --outDir ../dist/__data_harmonizer --base /mixs6.2_release_candidate/__data_harmonizer/
> 2023-10-03T14:50:36.8083181Z 
> 2023-10-03T14:50:37.0252115Z [36mvite v3.0.4 [32mbuilding for production...[36m[39m
> 2023-10-03T14:50:37.0902595Z transforming...
> 2023-10-03T14:50:40.3690301Z [32m✓[39m 10 modules transformed.
> 2023-10-03T14:50:40.3695634Z [31m[vite:json] Failed to parse JSON file, invalid JSON syntax found at line 1655660[39m
> 2023-10-03T14:50:40.3696692Z file: [36m/home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/schemas/mixs_6_2_rc.json[39m
> 2023-10-03T14:50:40.3721431Z [31merror during build:
> 2023-10-03T14:50:40.3722112Z Error: Failed to parse JSON file, invalid JSON syntax found at line 1655660
> 2023-10-03T14:50:40.3723287Z     at error (file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
> 2023-10-03T14:50:40.3724133Z     at throwPluginError (file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/rollup/dist/es/shared/rollup.js:21587:12)
> 2023-10-03T14:50:40.3724913Z     at Object.error (file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/rollup/dist/es/shared/rollup.js:22541:20)
> 2023-10-03T14:50:40.3725664Z     at Object.error (file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/rollup/dist/es/shared/rollup.js:21764:42)
> 2023-10-03T14:50:40.3726819Z     at Object.transform (file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:38838:22)
> 2023-10-03T14:50:40.3728189Z     at file:///home/runner/work/mixs6.2_release_candidate/mixs6.2_release_candidate/data_harmonizer/node_modules/rollup/dist/es/shared/rollup.js:22748:40[39m

**Comment by turbomam** [comment]
`jsonlint schemas/mixs_6_2_rc.json `

> schemas/mixs_6_2_rc.json:50134:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 50134, column 23, offset 1655599
> schemas/mixs_6_2_rc.json:50156:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 50156, column 23, offset 1656117
> schemas/mixs_6_2_rc.json:54936:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 54936, column 23, offset 1820001
> schemas/mixs_6_2_rc.json:54967:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 54967, column 23, offset 1822257
> schemas/mixs_6_2_rc.json:71711:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 71711, column 23, offset 2421239
> schemas/mixs_6_2_rc.json:73587:23: Warning: NaN literals are not allowed in strict JSON: 'NaN'
>    |  At line 73587, column 23, offset 2495065
> schemas/mixs_6_2_rc.json: ok, with warnings

**Comment by turbomam** [comment]
```json
        "assembly_qual": {
          "name": "assembly_qual",
          "annotations": {
            "Requirement": {
              "tag": "Requirement",
              "value": NaN
            }
          },
```

**Comment by turbomam** [comment]
I don't see any Requirement annotation on `assembly_qual` anywhere in generated-schema/mixs_6_2_rc.yaml

**Comment by turbomam** [comment]
I was looking for NaN, but in the schema, it's .nan

https://github.com/GenomicsStandardsConsortium/mixs6.2_release_candidate/blob/7fea329b6d2175f0193701e40a011bf1156cd4cd/generated-schema/mixs_6_2_rc.yaml#L20309-L20314

**Comment by turbomam** [comment]
scrub them from examples, too

**Comment by turbomam** [comment]
all in classes.SymbiontAssociated and classes.Agriculture
